### ISSUE TITLE
[BUG] Using Parcel to build/package generates a runtime TypeError

### ISSUE THREAD

**Issue by NVMKenneth** [twilio/twilio-voice.js#101]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
```js
...
import { Device } from '@twilio/voice-sdk'
...

...
private deviceConfig: Device.Options = {
    logLevel: 'DEBUG',
    tokenRefreshMs: 10 * 60 * 1000, // 10 minutes
    sounds: {
      incoming: 'REDACTED',
      disconnect: 'REDACTED'
    },
    closeProtection: true
  }
...

...
const device = new Device(token, this.deviceConfig)
...
```

```json
// tsconfig.json
...
"esModuleInterop": true,
...
````

**Expected behavior:**

Able to use Parcel as a build/packaging tool and have the SDK execute without TypeError. This error appears in a tab (not extension). The passed-in token and device values work fine.

**Actual behavior:**
When using parcel, I am getting a runtime TypeError.  If using Webpack, this error does not appear.
```js
TypeError: (this._options.AudioHelper || audiohelper_1.default) is not a constructor
```

Console log
```js
TypeError: (this._options.AudioHelper || audiohelper_1.default) is not a constructor
    at Device1._setupAudioHelper (device.ts:1304:19)
    at Device1.updateOptions (device.ts:791:10)
    at new Device1 (device.ts:539:10)
    at loginToTwilio (index.ts:154:21)
    at async ExecuteWrapper.invoke (Executor.ts:57:21)
    at async RetryPolicy.execute (RetryPolicy.ts:152:22)
    at async TwilioWebRTC.login (index.ts:56:7)
```

**Software versions:**

 - [x] Browser(s): Chrome
 - [x] Operating System: MacOS/Windows
 - [x] twilio.js: device.js
 - [x] Third-party libraries (e.g., Angular, React, etc.): Parcel, versions 2.5.0 and later (also tested with 2.6.2) in node various versions (16.15.0,18.x)

**Comment by mhuynh5757** [comment]
Thanks for bringing this to our attention @NVMKenneth, we're tracking this internally.

**Comment by ayyrickay** [comment]
I also ran into this issue while building the Twilio Dev Phone. I ended up just writing my own webpack config, but it's definitely frustrating. https://stackoverflow.com/questions/71256281/a-constructor-from-a-node-module-im-importing-works-when-using-create-react-app/73736170#73736170

**Comment by charliesantos** [comment]
Please check https://github.com/twilio/twilio-voice.js/issues/55#issuecomment-1571122310
Please feel free to follow up. If you have any questions.
