### ISSUE TITLE
[BUG] generated esm has invalid reference to map files

### ISSUE THREAD

**Issue by waynebrantley** [twilio/twilio-voice.js#103]
- [ x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

The following files reference a map file that does not exist, which causes warnings when building (and of course keep the map files from working).

AudioPlayer.js
Deferred.js
EventTarget.js

Suggest to include the map file in the package or remove the map reference

Here is a screenshot showing the reference and what files are shipped.

![image](https://user-images.githubusercontent.com/157082/183218193-01ffc010-736c-44ed-8fa5-65f708a13dbb.png)

**Comment by k-funk** [comment]
+1

This is blocking my project from upgrading some of our infrastructure. (webpack/create-react-app)

**Comment by charliesantos** [comment]
Submitted an internal ticket. Tracking this as part of https://github.com/twilio/twilio-voice.js/issues/147

**Comment by charliesantos** [comment]
@waynebrantley can you please try this RC version? https://github.com/twilio/twilio-voice.js/issues/55#issuecomment-1571122310
We're able to see source maps now properly in our svelte+vite and angular 16 projects.

**Comment by charliesantos** [comment]
SDK source maps work but the AudioPlayer source maps, which is a dependency, are still missing. We will be addressing them soon. Please stay tuned!

**Comment by waynebrantley** [comment]
@charliesantos I did a  test of the build.
I am happy to report I did not get any errors in building regarding map files.
However, I noticed a significant increase in bundle size which I will report on the other ticket.

**Comment by charliesantos** [comment]
Fixed in [2.6.0-rc2](https://github.com/twilio/twilio-voice.js/releases/tag/2.6.0-rc2)

**Comment by charliesantos** [comment]
We just released 2.6.0 which contains the fix for this issue.
