### ISSUE TITLE
Timing issue calling setInputDevice on newly created device; Firefox still unsupported?

### ISSUE THREAD

**Issue by ajporterfield** [twilio/twilio-voice.js#104]
What is the recommended way of calling setInputDevice on a newly created device?  I'm currently using the deviceChange event callback to set the input device.

    device.audio.on('deviceChange', () => {
      if (
        device.audio &&
        device.audio.availableInputDevices.get(deviceId)
      ) {
        device.audio.setInputDevice(deviceId);
      }
    });

On Chrome, this works most of the time, but I still get the following JS error at times.

```
Uncaught (in promise) TypeError: Failed to execute 'connect' on 'AudioNode': Overload resolution failed.
    at _._updateInputStreamSource (b5ab165.js:1:79247)
    at b5ab165.js:1:81198
```

In Safari, I'm always getting this JS error when calling setInputDevice in the deviceChange event callback after it's created.

`Unhandled Promise Rejection: TypeError: Type error`

setInputDevice doesn't work in Firefox, but I think that's intended behavior as there's a specific check/exception in the codebase for it.

I think this is a timing issue b/c I'm able to call setInputDevice successfully in Chrome and Firefox later during an outgoing call.  I would rather not rely on setTimeout to delay calling setInputDevice when a new device is created.  Is there a different device/call event I should be listening for (ex: call.on('accept', callback))?  Do I need to wait to call setInputDevice until after device.connect() is called?  Or maybe there's a different way of setting an audio deviceId through options that doesn't require calling setInputDevice.

I found [this example](https://www.twilio.com/docs/voice/sdks/javascript/best-practices#working-with-microphones-and-getusermedia), but we're just making outgoing calls - not registering and listening for incoming calls.

Any recommendations would be much appreciated.  Thanks!

**Comment by ajporterfield** [comment]
Settings the input device in call.on('accept', callback) is consistently working for me in Chrome and Safari, which is great.  

I just wanted to confirm with you that setInputDevice is indeed still unsupported in Firefox.  The bugzilla url referenced in the codebase is from 6 years ago and the conversation at the bottom of the thread seems to indicate the bug has been fixed and verified.  My Firefox version is now 103 which is quite a ways from version 51 referenced in the docs ("Note: This is not supported in Firefox (as recent as 51) due to its lack of support for multiple input devices.").  Have you tested setInputDevice on recent versions?  Thanks.

**Comment by hsavit1** [comment]
@ajporterfield any update on this?

**Comment by charliesantos** [comment]
Addressed in this branch. Watch out for when it's released.
https://github.com/twilio/twilio-voice.js/tree/feature/audio_processor
