### ISSUE TITLE
How to put call on hold for incoming and outgoing calls

### ISSUE THREAD

**Issue by yashbacancy** [twilio/twilio-voice.js#127]
It's likely not something we will implement SDK-side. So, how we can implement the hold feature on the server side? 
Also, I have already tried by using **Conference** objects but not able to create the conference. 
Can someone please guide in the same?

**Comment by charliesantos** [comment]
@yashbacancy please follow this [thread](https://github.com/twilio/twilio-voice.js/issues/32) instead.
