### ISSUE TITLE
NPM @twilio/voice-sdk Not Found [BUG]

### ISSUE THREAD

**Issue by craigp1231** [twilio/twilio-voice.js#13]
Just like the title suggests, the NPM @twilio/voice-sdk package cannot be found

![image](https://user-images.githubusercontent.com/4073362/124963007-33a12300-e017-11eb-87c8-1a4436065c6d.png)

**Comment by tim-lukacik** [comment]
I think they are in the middle of a major version change.

`npm i https://github.com/twilio/twilio-voice.js#2.0.0` should work in the meantime

**Comment by ryan-rowland** [comment]
Yes, sorry for any confusion here. As the README.md mentioned, we didn't publish the 2.0 pilot artifact to npm. Now that we have released 2.0 as GA, the package is available on npmjs [here](https://www.npmjs.com/package/@twilio/voice-sdk).
