### ISSUE TITLE
[FEATURE] Ability to mute sound effects from device config

### ISSUE THREAD

**Issue by tedg** [twilio/twilio-voice.js#131]
**Is your feature request related to a problem? Please describe.**
Though I can set the various sound effects to whatever I want via a URL, there is no way to explicitly mute them in the current version. The only way to do this from what I have found is to pass a dummy URL such as `https://example.com/silence.mp3`. This results sound never playing but also the browser tries to fetch from the URL.

**Describe the solution you'd like**
Mute a sound effect completely by passing something like `false` or `null` instead of a URL, or have a 2nd parameter `mute`.

**Describe alternatives you've considered**
```
device.updateOptions({
                sounds: {
                    outgoing: https://example.com/silence.mp3,
                    disconnect: https://example.com/silence.mp3,
                },
            });
```

**Additional context**
The default sounds are extremely annoying and that's why I am looking to mute the outgoing and disconnect sounds.

**Comment by mhuynh5757** [comment]
Hi @tedg, thanks for reaching out. Have you tried the `device.audio` API to disable sounds? Here is an example of how it could be used:
```ts
const device = new Device(...);
device.audio.disconnect.enabled(false);
```

**Comment by tedg** [comment]
Tried that out, got the following error:
```
Uncaught TypeError: device.audio.disconnect.enabled is not a function
```

**Comment by mhuynh5757** [comment]
Hi @tedg, apologies for the miscommunication. Please try the following API
```
device.audio.disconnect(false);
```

**Comment by charliesantos** [comment]
Closing this now. Please feel free to follow up if you have any further questions.
