### ISSUE TITLE
How to use AMD (Answering Machine Detection) with twilio-voice? 

### ISSUE THREAD

**Issue by sensboston** [twilio/twilio-voice.js#136]
Could you please provide a small snippet how to use AMD feature, as described in the [API reference](https://www.twilio.com/docs/voice/answering-machine-detection)? I can't find any reference to this feature on twilio-voice library.

Thanks a lot!

**Comment by charliesantos** [comment]
Thanks for reaching out @sensboston . This is the Twilio Voice JS SDK that runs on the browser and does not interface with AMD. Please submit a support ticket and our support team will be happy to help!
