### ISSUE TITLE
[BUG] Unable to start an outbound call 

### ISSUE THREAD

**Issue by dinoluck** [twilio/twilio-voice.js#137]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Using latest @twilio/voice-sdk, when running this:

```js
 device = new Device(token)
    await device
      .connect({
        params: {
          to: phoneNumber,
        },
      })
      .then((data) => console.log('Call then', data))
      .catch((data) => console.log('Call error', data))
```

The call fails and I am catching following in the catch():

```
Call errored TypeError: 'get' on proxy: property '_operations' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<AsyncQueue2>' but got '#<AsyncQueue2>')
    at Proxy.stop (sound.js:226:8)
    at Proxy.<anonymous> (device.ts:576:53)
    at step (sound.js:243:18)
    at Object.next (sound.js:243:18)
    at fulfilled (sound.js:243:18)
```
Which refers to this part of the SDK package:
```js
// Stop the incoming sound if it's playing
this._soundcache.get(Device.SoundName.Incoming).stop();
```

EDIT: From what I see there are many methods (in this case _operation) that are not writeable and that is why this is failing.

 [x] Browser: Chrome109.0.5414.74 (Official Build) (64-bit)
 [x] Operating System: Windows 11 22623.746
 [x] @twilio/voice-sdk ^2.2.0:

**Comment by charliesantos** [comment]
Hi @dinoluck , can you please double check the example code? I don't think the device object doesn't have a `phone` property? https://twilio.github.io/twilio-voice.js/classes/voice.device.html

**Comment by dinoluck** [comment]
> Hi @dinoluck , can you please double check the example code? I don't think the device object doesn't have a `phone` property? https://twilio.github.io/twilio-voice.js/classes/voice.device.html

It's mistype, the place I hold it is called "device.phone", updated code for clarity.

**Comment by charliesantos** [comment]
Thanks for clarifying @dinoluck . Unfortunately, we are not able to reproduce this issue. Most of our customers also run this same snippet and we haven't received any report of this error. Are you able to reproduce it using our quickstart? https://www.twilio.com/docs/voice/sdks/javascript/get-started
Also,
are you running our SDK with other libraries?
are you loading it via npm or cdn?
are you able to reproduce this on other browsers or machine such as mac?
lastly, can you please enable debug mode and provide the whole logs, from the time you load the app up to when you get this error?
