### ISSUE TITLE
calling from web to mobile devices

### ISSUE THREAD

**Issue by firzshkh** [twilio/twilio-voice.js#146]
Im trying to call a random mobile device from web browser using twilio.
Does twilio allows us to call a number and communicate same as a cellular call or just as a message delivering or automated calling system?
Tried using twilio-voice-sdk with its create function and twiml

**Comment by charliesantos** [comment]
Hi @firzshkh thanks for reaching out! You certainly can call a number and communicate same as a cellular or a landline call! You can build a web app or mobile apps that allows you to do this. Please check our quickstarts to get you up and running quickly. https://www.twilio.com/docs/voice/sdks#quickstarts
