### ISSUE TITLE
[BUG] building issues where is twilio.js?

### ISSUE THREAD

**Issue by taf2** [twilio/twilio-voice.js#148]
Crackling~/work/twilio-voice.js (master)> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: typedoc-plugin-external-module-name@3.0.0
npm ERR! Found: typedoc@0.16.11
npm ERR! node_modules/typedoc
npm ERR!   dev typedoc@"0.16.11" from the root project
npm ERR!   peer typedoc@">=0.7 <1.11.1" from typedoc-plugin-as-member-of@1.0.2
npm ERR!   node_modules/typedoc-plugin-as-member-of
npm ERR!     dev typedoc-plugin-as-member-of@"1.0.2" from the root project
npm ERR!   1 more (typedoc-plugin-internal-external)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typedoc@">=0.7.0 <0.15.0" from typedoc-plugin-external-module-name@3.0.0
npm ERR! node_modules/typedoc-plugin-external-module-name
npm ERR!   dev typedoc-plugin-external-module-name@"3.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typedoc@0.14.2
npm ERR! node_modules/typedoc
npm ERR!   peer typedoc@">=0.7.0 <0.15.0" from typedoc-plugin-external-module-name@3.0.0
npm ERR!   node_modules/typedoc-plugin-external-module-name
npm ERR!     dev typedoc-plugin-external-module-name@"3.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/taf2/.npm/_logs/2023-03-23T20_02_08_956Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taf2/.npm/_logs/2023-03-23T20_02_08_956Z-debug-0.log
Crackling~/work/twilio-voice.js (master)> node --version
v19.8.1
Crackling~/work/twilio-voice.js (master)>

**Comment by charliesantos** [comment]
@taf2 please install the dependencies with `--legacy-peer-deps` flag
```
npm install --legacy-peer-deps
```
Then run
```
npm run build
```

The root folder can then be used to install using npm locally
```
cd your_project
npm install /path-to-my-repositories/twilio-voice.js
```

Or you can host the twilio.js file from the `dist` folder.

See our build pipeline for more details https://github.com/twilio/twilio-voice.js/blob/master/.circleci/config.yml

**Comment by charliesantos** [comment]
Closing since this has already been answered.

**Comment by taf2** [comment]
Any reason Twilio doesn't just have builds available to download?

**Comment by charliesantos** [comment]
@taf2 the builds are available via npm, or in the release page https://github.com/twilio/twilio-voice.js/releases
