### ISSUE TITLE
[problem] How to Enable Dual-Channel Recording in the Browser

### ISSUE THREAD

**Issue by Bain-liu** [twilio/twilio-voice.js#173]
I want to enable dual-channel recording in the browser so that I can obtain a dual-track recording file. How can I do that?

version：@twilio/voice-sdk ^2.0.1

**Comment by charliesantos** [comment]
Hi @Bain-liu thanks for reaching out! I'm not sure what you meant by "recording in the browser" but Twilio Programmable Voice support dual channel recordings. Please see the following pages and let us know if this answers your question.
- https://www.twilio.com/en-us/changelog/dual-channel-voice-recordings-by-default
- https://www.twilio.com/docs/voice/api/recording

**Comment by charliesantos** [comment]
Closing since this has already been answered. Please feel free to follow up.
