### ISSUE TITLE
[BUG] Breaking change in the "Enabled Sounds" state due to AudioHelper change

### ISSUE THREAD

**Issue by kamalbennani** [twilio/twilio-voice.js#178]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

This [PR](https://github.com/twilio/twilio-voice.js/pull/153) has introduced a breaking change making the **enabledSounds** state not persist when calling the `device.updateOptions` function.

`device.updateOptions` recreate a new Instance of the AudioHelper each time this method is called, and because now the `enabledSounds` state is stored on the AudioHelper class, this state doesn't persist as it used to be.

A simple solution, would be to pass the enabledSounds to the new AudioHelper instance before destroying the previous one.

What do you think?

The issue was introduced in v2.4.0

**Software versions:**

 - [x] Browser(s): Arc Version 0.110.1 (39837) / Chromium Engine Version 114.0.5735.198
 - [x] Operating System: MacOS 
 - [x] twilio.js: 2.5.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by charliesantos** [comment]
Hey @kamalbennani thanks for reporting. We will take a look and consider your suggestion.
Prior to v2.4.0, `device.updateOptions` do not work anyway due to this bug correct? https://github.com/twilio/twilio-voice.js/issues/14
Let me know if you're seeing the same behavior.

**Comment by kamalbennani** [comment]
Hi @charliesantos 
It used to work, the API was just not exposed via TS if I recall.
But now, the API looks good but a new regression has been introduced.
I can push a fix if you want to?

**Comment by charliesantos** [comment]
Hey @kamalbennani yes feel free to submit a PR and I will review.
