### ISSUE TITLE
Would like to know if twilio-min.js 2.5.0 version supports Outbound calls ?

### ISSUE THREAD

**Issue by vkrishn1finvi** [twilio/twilio-voice.js#187]
Hi Team,

I came across the PR raised by your colleague to resolve Citrix VDI issue and curious to know if the latest version of twilio-min.js i.e 2.5.0 supports Outbound calls too as I see 1.15.x version does not support.

Please let me know at the earliest.

Thanks in advance.

**Comment by mhuynh5757** [comment]
Hi @vkrishn1finvi thanks for reaching out! Please consider using the latest `2.x` version of the SDK and not `2.5.0` or `1.x`. The latest version will always have the best features and bugfixes.

As for Genesys cloud, we have not tested with that specific VDI provider, only with Citrix. However, if their SDK and WebRTC shims are compliant, it should work.

**Comment by vkrishn1finvi** [comment]
@mhuynh5757  when we say ```2.x``` which specific version I can use. Please confirm

**Comment by kbagchiGWC** [comment]
@vkrishn1finvi [2.7.1](https://www.twilio.com/docs/voice/sdks/javascript/changelog#271-august-3-2023) is the latest version of the Twilio Voice JavaScript SDK.

If your question is answered, please close the issue. Thank you.

**Comment by vkrishn1finvi** [comment]
> @vkrishn1finvi [2.7.1](https://www.twilio.com/docs/voice/sdks/javascript/changelog#271-august-3-2023) is the latest version of the Twilio Voice JavaScript SDK.
> 
> If your question is answered, please close the issue. Thank you.

@kbagchiGWC  thanks, can anyone confirm on Geneysys Cloud too plaese as we are migrating to genesys cloud.

**Comment by vkrishn1finvi** [comment]
> > @vkrishn1finvi [2.7.1](https://www.twilio.com/docs/voice/sdks/javascript/changelog#271-august-3-2023) is the latest version of the Twilio Voice JavaScript SDK.
> > If your question is answered, please close the issue. Thank you.
> 
> @kbagchiGWC thanks, can anyone confirm on Geneysys Cloud too plaese as we are migrating to genesys cloud.

@kbagchiGWC @mhuynh5757 - could you please confirm above and also, thing is we have been using the twilio.min.js 1.7 version till date so when I had downloaded the latest 2.7.1 version, I navigated to the path and I assumed that we can use the twilio.min.js file itself from dist folder is my understanding correct ? or should i use twilio.js as well to support citrix VDI ?

As we were historically using twili.mim.js 1.7 version just wanted double check if just twilio.min.js 2.7.1 is fine or should I include twilio.js as well. ?


![image](https://github.com/twilio/twilio-voice.js/assets/110710669/144affae-7ac0-4a6b-ad93-518f6c68dac8)

**Comment by vkrishn1finvi** [comment]
@mhuynh5757 @kbagchiGWC - After bumping the library version into our App by copying the twilio.min.js from 2.7.1 we see following issue. This fn was working fine with 1.7.6 version earlier.

![image](https://github.com/twilio/twilio-voice.js/assets/110710669/90ce7642-0103-4928-bab8-0b195b79805c)

**Comment by mhuynh5757** [comment]
Hi @vkrishn1finvi thanks for reaching out. Unfortunately we have not tested with Genesys cloud and it is not in our immediate roadmap.

The various `.js` files in the `dist/` folders are all built and bundled versions of our SDK, they are all usable. I would recommend that you use the `.min.js` file in production, as they are "minified" meaning they are smaller and will result in faster page loads for your end-users. It has all the same functionality as the normal `.js` file.

The error that you're encountering is because there are many breaking changes between our `1.x` and `2.x` projects. One of which is the removal of `Device.setup`, please see this migration guide for more details.

https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20#stop-using-the-device-singleton-and-instead-instantiate-a-new-device-instance

Thanks for using our project and reaching out! I would like to request that we close this issue since the original problem has been solved, if you have further issues please open another one.

**Comment by vkrishn1finvi** [comment]
> Hi @vkrishn1finvi thanks for reaching out. Unfortunately we have not tested with Genesys cloud and it is not in our immediate roadmap.
> 
> The various `.js` files in the `dist/` folders are all built and bundled versions of our SDK, they are all usable. I would recommend that you use the `.min.js` file in production, as they are "minified" meaning they are smaller and will result in faster page loads for your end-users. It has all the same functionality as the normal `.js` file.
> 
> The error that you're encountering is because there are many breaking changes between our `1.x` and `2.x` projects. One of which is the removal of `Device.setup`, please see this migration guide for more details.
> 
> https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20#stop-using-the-device-singleton-and-instead-instantiate-a-new-device-instance
> 
> Thanks for using our project and reaching out! I would like to request that we close this issue since the original problem has been solved, if you have further issues please open another one.

Thanks @mhuynh5757 . Few minutes ago I started taking a look at same wiki. I'm falling short to solve a production issue. Is there a example client code using the latest 2.7.1 I can take a look and quickly map our code accordingly ?

Sure, once this is addressed will close in next 2-3 days.

**Comment by vkrishn1finvi** [comment]
@mhuynh5757  thank you so much for the support. I did the changes and now i see while clicking Dialpad would like to know as why this error appears.

![image](https://github.com/twilio/twilio-voice.js/assets/110710669/3bb19a56-acc1-4850-ae2d-6cefde400c9d)

**Comment by vkrishn1finvi** [comment]
> 
@mhuynh5757 @kbagchiGWC can i Expect a response today for above issue. Basically, Call object does not give any info regarding call status and tried writing with ```accept``` but it does not work.

```
v

**Comment by charliesantos** [comment]
Closing since the original question has been answered. Please submit a different ticket for any new issues.
