### ISSUE TITLE
[BUG][Vue] I couldn't make the outbound call

### ISSUE THREAD

**Issue by domadev812** [twilio/twilio-voice.js#189]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
device.connect({
To: phoneNumber
})
```

**Expected behavior:**

I couldn't make the outbound call.

**Actual behavior:**

```
When I try to create the outbound call, I get the issue something like this

'get' on proxy: property '_operations' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#' but got '#')
```

It is happened after I call the device.connect()

**Software versions:**

 - [x] Browser(s):
 - [x] Operating System:
 - [x] twilio.js:
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by domadev812** [comment]
FYI: I can get the inbound call. This is only happened when I try to make the outbound call.

**Comment by mhuynh5757** [comment]
Hi @domadev812 thanks for reaching out, apologies for the delay in response. Could you please fill out the "software versions" section of your issue request? It would help debug this issue further, I suspect that a framework or other 3rd party library you're using may be causing this.

**Comment by domadev812** [comment]
@mhuynh5757 
I have been working in Vue3.x project.

if I create the TwilioDevice variable in one file, it works well now.
ex: Phone.vue
```
const device = new Device(****).
******
device.value.connect({params})
```

But if I create the device in the Composition and use it in another file, I get the above issue.
Ex:
- Composition file - useTwilio
```
const device: Ref<Device | null> = ref(null)
device.value = new Device(****)
```

- Phone.vue
```
const { device } = useTwilio()
******
device.value.connect({params})
```

**Comment by charliesantos** [comment]
@domadev812 this seems to be an issue specific to vue, not on the SDK. However, we are happy to help and consider making some tweaks on the SDK if necessary. Have you found out any vue specific requirements regarding how objects should be exported in the manner you described? Or is your Example#1 enough for your use case for now?

**Comment by charliesantos** [comment]
Closing since this is vue specific and inactivity. Feel free to follow up with the requested information if needed.
