### ISSUE TITLE
"Error: port is undefined" in Firefox

### ISSUE THREAD

**Issue by tim-lukacik** [twilio/twilio-voice.js#19]
After accepting a call the console gets flooded with this error message.

![image](https://user-images.githubusercontent.com/11653955/127360823-54683c11-51e7-4b07-a571-0c16fe1dfcfb.png)

**Comment by ryan-rowland** [comment]
Hi @tim-lukacik,
We haven't seen this issue on our end. It looks like you didn't fill out the default issue template for bug reports; there's not really enough information here for us to investigate.

**Comment by ryan-rowland** [comment]
Closing this as I haven't received any more information.
