### ISSUE TITLE
Twilio.Device.connect emits call object but call.on fails

### ISSUE THREAD

**Issue by vkrishn1finvi** [twilio/twilio-voice.js#190]
Hi Team,

I'm using following code:

```
const call = twilioVoiceComponentController.globalDevice.connect({
    params: {
        phone: customerPhoneNumber.split('-').join('wwww').replace(/[^w\+0-9]/g, ''),
        phoneForPhoneMap: payload.phone,
        /* Extract this information from the POST body and create necessary TOD's via API.*/
        agentLoginName: userInfo.data.loginName,
        accountNum: Cmc.registry.get("acctNum"),
        currentResponsibleId: Cmc.registry.get("currentResponsibleId"),
        contactPhoneId: payload.contactPhoneId || 0,
        phoneTypeId: payload.phoneTypeId || 0,
        isDialPad: payload.isDialPad || false
    },
    rtcConstraints: {
        audio: true
    },
    logLevel: 1
})
```

When I do :

```
call.on('accept', customeFn);

```

It says, .on function is not defined. Actually call object is not yielding any status of the call too. Need quick support. I had mentioned regarding this in this PR as well # https://github.com/twilio/twilio-voice.js/issues/187#issuecomment-1687896834  wherein no response is attained..

**Comment by mhuynh5757** [comment]
Hi @vkrishn1finvi thanks for reaching out. `device.connect` is an `async` function, therefore it must be `await`ed or chained with a `.then` to get the call object. Please see the official API docs for more information on the call signatures of our SDK.

https://twilio.github.io/twilio-voice.js/index.html

**Comment by vkrishn1finvi** [comment]
> Hi @vkrishn1finvi thanks for reaching out. `device.connect` is an `async` function, therefore it must be `await`ed or chained with a `.then` to get the call object. Please see the official API docs for more information on the call signatures of our SDK.
> 
> https://twilio.github.io/twilio-voice.js/index.html

thanks @mhuynh5757 . It worked now. But now what I see is that before call gets accepted or disconnected following custom fn mentioned in accept gets exe

**Comment by vkrishn1finvi** [comment]
> Hi @vkrishn1finvi thanks for reaching out. `device.connect` is an `async` function, therefore it must be `await`ed or chained with a `.then` to get the call object. Please see the official API docs for more information on the call signatures of our SDK.
> 
> https://twilio.github.io/twilio-voice.js/index.html

thanks @mhuynh5757 . It worked now. But now what I see is that before call gets accepted following custom fn mentioned in accept gets executed.

```
}).then((Call) => {
                            // As per Twilio new 2.7.x version we should start relying on accept on call as well.
                            Call.on("accept", twilioVoiceComponentController.onAcceptHandler(payload, Call));
                            console.log("twilioVoiceComponentController.globalDevice call has been initiated");
                            });

Also, I see none of the method works on device object this is our code any reason why ?

```
initializeTwilioDevice: function(payload) {
        return new Promise(function(resolve) {
            if(!twilioVoiceComponentController.supportsWebRTC()) {
                resolve();
            } else {
      
	  
	  twilioVoiceComponentController.globalDevice = new Twilio.Device(payload.accessToken);
        twilioVoiceComponentController.globalDevice.updateOptions({codecPreferences: ['opus','pcmu'], maxAverageBitrate:16000,
            allowIncomingWhileBusy: false, debug: true, closeProtection: true});
        twilioVoiceComponentController.globalDevice.on('registered', function(device) {
            console.log('Twilio: Twilio.Device is initialized and ready.');
            twilioVoiceComponentController.showCallIcons();
        });

                /** changes start
                 * Based on the twilio.min.js API migration docs: https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice
                 * Altered the Twilio fn's.
                 *
                 * As per latest version, we should not be using singleTon object therefore, creating a device object.
                 */

                twilioVoiceComponentController.globalDevice.on('error', function(error) {
                    console.log('Twilio Device: Error occurred: ', error);
                    twilioVoiceComponentController.performAction('agent.call-cleanup');
                    twilioVoiceComponentController.resetCurrentAgentObjectInLocalStorage();
                    twilioVoiceComponentController.resetToolbar();
                    twilioVoiceComponentController.hideCallIcons();
                });


            // show dispositon when connect / accept now in new API

                twilioVoiceComponentController.globalDevice.on('disconnect', function() {
                    console.log("globalDevice.addListener with disconnect");
                    console.log('Twilio Device disconnected (or may be call)');
                    twilioVoiceComponentController.hangupDialPadCall('Call Ended', false);
                    twilioVoiceComponentController.performAction('agent.call-cleanup');
                });
                twilioVoiceComponentController.globalDevice.on('offline', function() {
                    console.log("globalDevice.addListener with offline state");
                    console.log('Twilio Device is offline.');
                    twilioVoiceComponentController.performAction('agent.call-cleanup');
                    twilioVoiceComponentController.resetCurrentAgentObjectInLocalStorage();
                    twilioVoiceComponentController.resetToolbar();
                    twilioVoiceComponentController.hideCallIcons();
                });

                twilioVoiceComponentController.globalDevice.on('incoming', function(connection) {
                    console.log("globalDevice.addListener with incoming state");
                    console.log('connection: ', connection);
                    twilioVoiceComponentController.direction = 'inbound';
                    twilioVoiceComponentController.inboundCallConnection = connection;
                    /* show the modal here */
                    Swal.fire({
                        title: 'Incoming Call from: ' + connection.parameters.From,
                        html: '<br/><div class="incoming-phone-body">'
                                    + '<i class="phone-icon is-animating" id="answerCallButton"></i>'
                                    + '<span class="phone-hang-up-icon" id="hangupCallButton"></span>'
                                + '</div><br/>'
                                + '<div>Call will auto hang-up in <strong></strong> seconds.</div>',
                        timer: 30000,
                        allowOutsideClick: false,
                        allowEscapeKey: false,
                        allowEnterKey: false,
                        position: 'top-end',
                        width: '350px',
                        heightAuto: false,
                        customClass: {
                            container: 'swal-container-call-incoming'
                        },
                        onBeforeOpen: function() {
                            var content = Swal.getContent();
                            var $ = content.querySelector.bind(content);
                            var answer = $('#answerCallButton');
                            var hangup = $('#hangupCallButton');
                            Swal.showLoading();
                            answer.addEventListener('click', function() {
                                Swal.stopTimer();
                                /* 'connection' related actions start here. */
                                /* Accept calls only in 'queueView' */
                                /* Everywhere else, just broadcast the event */
                                if(window.currentViewName === 'queueView') {
                                    connection.accept();
                                    console.log('Connection accepted..');
                                    twilioVoiceComponentController.registerConnectionHandler(connection);
                                } else {
                                    twilioVoiceComponentController.updateActionInLocalStorage({
                                        'action': 'call.answered',
                                        'payload': null
                                    });
                                    /*
                                    * The handler function should execute this code.
                                    *
                                    * on 'call.answered'
                                    * twilioVoiceComponentController.connection && twilioVoiceComponentController.connection.accept && twilioVoiceComponentController.connection.accept();
                                    * twilioVoiceComponentController.registerConnectionHandler(twilioVoiceComponentController.connection);
                                    *
                                    * on 'call.rejected'
                                    * twilioVoiceComponentController.connection && twilioVoiceComponentController.connection.reject && twilioVoiceComponentController.connection.reject();
                                    *
                                    */
                                }
                                /* 'connection' related actions end here.*/

                                Swal.close();
                            });
                            hangup.addEventListener('click', function() {
                                Swal.stopTimer();

                                /* 'connection' related actions start here. */
                                if(window.currentViewName === 'queueView') {
                                    connection.reject();
                                    console.log('Connection rejected..');
                                } else {
                                    twilioVoiceComponentController.updateActionInLocalStorage({
                                        'action': 'call.rejected',
                                        'payload': null
                                    });
                                }
                                /* 'connection' related actions end here. */

                                Swal.close();
                            });

                            twilioVoiceComponentController.timerInterval = setInterval(function() {
                                Swal.getContent().querySelector('strong').textContent = (Swal.getTimerLeft() / 1000).toFixed(0);
                            }, 100);
                        },
                        onClose: function() {
                            clearInterval(twilioVoiceComponentController.timerInterval);
                        }
                    }).then(function(dismissReasonObject){
                        console.log('Dismissed modal with: ', dismissReasonObject);
                        if(dismissReasonObject && dismissReasonObject.dismiss && (dismissReasonObject.dismiss === Swal.DismissReason.timer)){
                            console.log('Auto hang-up the call here.');
                            connection && connection.reject && connection.reject();
                        }
                    });
                });
                resolve();
            }
        });
    },
```

I had referred this PR # https://github.com/twilio/twilio-voice.js/issues/78 and implemented the same but seems nothing works. Any best referece ? Currently I'm stuck on listeners and methods on Device and call object does not work as expected.
