### ISSUE TITLE
Twilio 2.7.1 outbound calls audio is not working 

### ISSUE THREAD

**Issue by vkrishn1finvi** [twilio/twilio-voice.js#193]
we are seeing following error: https://www.twilio.com/docs/api/errors/53405

we are blocked while making the outbound calls on Citrix we see though calls are placed, user is not able to hear the calls in Citrix with Edge and Chrome.

This is our code:

twilioVoiceComponentController.globalDevice.connect({
                            params: {
                                phone: customerPhoneNumber.split('-').join('wwww').replace(/[^w\+0-9]/g, ''),
                    
                            },
                            rtcConstraints: {
                                audio: true
                            },
                            logLevel: 1
                        }).then((twilioCall) => {
                            // As per Twilio new 2.7.x version we should start relying on accept on call as well.
                            twilioCall.on("accept", twilioVoiceComponentController.onAcceptHandler(payload, twilioCall));
                            console.log("Call has been connected and same fn has been invoked.");

                            // As per Twilio new 2.7.x version we should start relying on disconnect on call as well
                            twilioCall.on("disconnect", twilioVoiceComponentController.hangupDialPadCall('Call Ended', false));
                            console.log('Twilio Device disconnected (or may be call) and same fn has been invoked');

                        });

**Comment by mhuynh5757** [comment]
Hi @vkrishn1finvi thanks for reaching out. Please see the changelog entry for how to use the VDI WebRTC shims. https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md#webrtc-api-overrides-beta
