### ISSUE TITLE
Volume Settings For Sound Effects & Voice

### ISSUE THREAD

**Issue by JAD3N** [twilio/twilio-voice.js#196]
**Is your feature request related to a problem? Please describe.**
Sound effects can be too loud when wearing headphones for some users depending on the speakers etc, controlling this by the system causes problems if they use any other product that provides audio in the browser since it affects everything.

**Describe the solution you'd like**
I believe 2 controllable options for sound volume and voice volume in the device class would ideally solve the problem.

**Describe alternatives you've considered**
I've currently replacing the `Sound` option in device options with a custom class, but something built-in would be more ideal.

**Additional context**
I was surprised to find that this setting wasn't already built-in. Volume controls are almost a must for any web-based voice application since audio set-ups vary so much.

**Comment by charliesantos** [comment]
Hi @JAD3N , thanks for submitting. This has been considered, however, we are not getting enough demands from customers about this feature, making it a low priority for us. But let's keep this ticket open and see if we get more traction.

Just to confirm, by "sound volume" you mean these [sounds](https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice#deviceoptionssounds-properties-and-default-sounds) correct?
And by "voice volume" you mean, the audio that plays out during a call, e.g. the callee's voice, is this correct?

**Comment by JAD3N** [comment]
> Just to confirm, by "sound volume" you mean these [sounds](https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice#deviceoptionssounds-properties-and-default-sounds) correct?
> And by "voice volume" you mean, the audio that plays out during a call, e.g. the callee's voice, is this correct?

Yes, that's what I meant. Having a separate volume option for the sound effects like those would be great, since sometimes when a caller is too quiet you would want to boost the volume of the caller but not the sound effects.

Since it would be a low priority task, would submitting a PR for this feature help move this request along?

**Comment by charliesantos** [comment]
First step would be to collaborate with the public facing APIs, then we can discuss about implementation details after.
But before going to that route, let's see if we have some alternatives.

There's a `call.on('audio', handler)` API that provides the audio element used for the remote audio. You can use that audio element with an AudioContext, and increase the volume by adjusting the gain value. Don't forget to release any resources after each call to prevent any memory leaks.

**Comment by charliesantos** [comment]
Closing this now. We're tracking this feature request internally. Please feel free to follow up if needed.
