### ISSUE TITLE
[BUG] Crackling audio issue on chrome when zoom is running

### ISSUE THREAD

**Issue by charliesantos** [twilio/twilio-voice.js#197]
Crackling audio issue on chrome when zoom is running.

Steps to reproduce:
1) Create a zoom meeting and join
2) Make a Twilio Voice Call using the JS SDK
3) Notice the audio crackling sound

SDK version: 2.7.1

We have identified that this is due to a chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=1474865
To mitigate the issue, we are currently exploring solutions that will prevent calling MediaDevice APIs during a call.

**Comment by charliesantos** [comment]
@kamalbennani-aircall I see your team filed the chromium issue. Is what I described above similar to what you're seeing?

**Comment by tigranaircall** [comment]
Hi @charliesantos. Yes, you're correct, and thank you for pointing that out. The issue you described is indeed similar to what we're experiencing. Our team has filed a Chromium issue to address this problem.
Very good news. We would appreciate it a lot if your team could find a solution.

**Comment by gruckion** [comment]
I also found this is the case too. With the old or new API if I had youtube music open it would cause the Twilio audio to crack.

**Comment by charliesantos** [comment]
fixed in 2.7.2
