### ISSUE TITLE
Disconnected event not fired when caller disconnects

### ISSUE THREAD

**Issue by tim-lukacik** [twilio/twilio-voice.js#20]
I have the code below in my "incoming" event handler on the device
```
    onDeviceIncoming = (call) => {
        call.on('accept', () => { debugger });
        call.on('disconnect', () => { debugger });
        call.on('cancel', () => { debugger })
        call.on('error', () => { debugger })
```
The accept event fires correctly. After the call is accepted, if the caller hangs up on the agent, none of the other events seem to fire. I have also tried listening for connected/disconnected on the device itself with no luck.

**Comment by tim-lukacik** [comment]
Looking closer at the source I see this is a misunderstanding on my part. I imagined the call being like a cell phone, where the call is ended when either party hangs up. The behavior appears to be more like a landline, where the call exists until both parties hang up. Maybe this is because I'm accepting the call with reservation.conference()? It's a little confusing because the browser client makes a tone when the caller hangs up, but no event is fired that I can find.

**Comment by gauravumrani** [comment]
I am facing the same problem

**Comment by gauravumrani** [comment]
Any solution? or workaround?

**Comment by karan-bacancy** [comment]
@gauravumrani what's solution you have applied.. i have faced same issue

**Comment by karan-bacancy** [comment]
@tim-lukacik  what's solution you have applied.. i have faced same issue

**Comment by charliesantos** [comment]
@karan-bacancy are you using conference? If so, you need handle that on the server.
