### ISSUE TITLE
how do i make conference call 

### ISSUE THREAD

**Issue by Harshdeep9821** [twilio/twilio-voice.js#200]
I can able to make voice call  by 
 params = {
      To: number,
      From: "+XXXXXXXXXXXX",
    }

  const twilioCall = await device.connect({params});
But how can I Make Conference call. 
I tryed 
 const twilioCall = await device.connect({To: `conference:${sessionIDD}`});
 const twilioCall = await device.connect(params:{{To: `conference:${sessionIDD}`}});
 const twilioCall = await device.connect({params:{conference:sessionIDD}});

But Every time i try Call disconnect

**Comment by charliesantos** [comment]
The device.connect() method sends the parameters to the [Token’s TwiML App’](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node/blob/b1cb14a30da7bc243431e6c1167797bf1fc2cb37/.env.example#L11)s Voice URL. It doesn’t control call behavior. I’d recommend you read over [this doc](https://www.twilio.com/docs/voice/sdks#build-a-voice-sdk-application) to understand how the Voice SDK and TwiML interact.
In [this quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node), for example, the device.connect() method causes Twilio to send an HTTP request to [this endpoint](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node/blob/b1cb14a30da7bc243431e6c1167797bf1fc2cb37/src/router.js#L10). The endpoint returns TwiML instructions to Twilio, which is generated by [this function](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node/blob/b1cb14a30da7bc243431e6c1167797bf1fc2cb37/src/handler.js#L32). Notice how the params passed in device.connect() are used in this function to create <Dial><Number> or <Dial><Client> TwiML. You can modify your TwiML endpoint to check for the presence of a conference param and generate the  [<Conference> TwiML instructions](https://www.twilio.com/docs/voice/twiml/conference) you want.
