### ISSUE TITLE
Question: replacement for removed device events

### ISSUE THREAD

**Issue by electrovir** [twilio/twilio-voice.js#201]
I've got old code that is using the old [`twilio-client` (v1)](https://www.npmjs.com/package/twilio-client) package and is listening to the following events on a Twilio `Device`:

1. `device.on('connect'`
2. `device.on('disconnect'`
3. `device.on('cancel'`

I've read [the migration guide](https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20) and [the changelog](https://www.twilio.com/docs/voice/sdks/javascript/changelog) and I see no notes anywhere about the mentioned `Device` events being replaced. I simply see that in the new API they no longer exist.

What do I need to use instead for each of those events?

**Comment by charliesantos** [comment]
Hi @electrovir , thanks for submitting! We are currently improving our migration guide to address any gaps similar to this.
To answer your question, the device events you mentioned are the same exact events that are emitted by the `Connection` object. We only bubble up these events to the `Device` object.

Now in 2.x, we no longer bubble up these events but you can still listen to them via the `Call` object (previously knows as `Connection`). Please see https://www.twilio.com/docs/voice/sdks/javascript/twiliocall#events
Also, please note that `device.on('connect'` is the same as `call.on('accept`

**Comment by electrovir** [comment]
Awesome, that seems to be doing the trick! Thank you!
