### ISSUE TITLE
[FEATURE] Twilio Voice on Embedded Device

### ISSUE THREAD

**Issue by alberk8** [twilio/twilio-voice.js#205]
**Is your feature request related to a problem? Please describe.**
A C programming language of Twilio Voice on embedded device with MCU like ESP32, STM32, etc

**Describe the solution you'd like**
Ability to connect to Twilio Voice to make and receive voice on MCU based device that is agnostic on the Transport medium (ie wifi, mobile, ethernet)

**Describe alternatives you've considered**
Using WebRTC on MCU but that necessitate me to build out a backend infrastructure.

**Comment by charliesantos** [comment]
Thanks @alberk8 . This is currently not in our roadmap, but we will consider it.

**Comment by charliesantos** [comment]
This has been brought up internally and no further action is required in this ticket. But feel free to follow up in the future if needed.
