### ISSUE TITLE
[BUG] Call Disconnected event sent when accepting call if there are more than one incoming call

### ISSUE THREAD

**Issue by tejinder-sarna** [twilio/twilio-voice.js#208]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
const TWILIO_VOICE_OPTIONS = {
  closeProtection: true,
  allowIncomingWhileBusy: true,
  edge: "roaming",
  logLevel: "debug",
  maxAverageBitrate: 0,
  maxCallSignalingTimeoutMs: 30000,
  tokenRefreshMs: 60000,
};

new Device(token, TWILIO_VOICE_OPTIONS);
```

**Expected behavior:**

If there are two incoming calls, and we accept one, Twilio voice should connect to the call and send a "call connected" event.

**Actual behavior:**

Twilio voice sends a "call disconnected" event BUT the call is connected and users can hear each other.
If the caller hangs up the call, Twilio voice prints this error in the console

```js
call.js:324 Uncaught TypeError: Cannot read properties of null (reading 'pc')
```

**Debug logs:**
```
 Setting up VSP
 Initializing preferred transport backoff using config:  {factor: 2, maxDelay: 1000, randomisationFactor: 0.4}
 Initializing primary transport backoff using config:  {factor: 2, initialDelay: 100, maxDelay: 20000, randomisationFactor: 0.4}
 WSTransport.open() called...
 Attempting to connect...
 Closing and cleaning up WebSocket...
 No WebSocket to clean up.
 WebSocket opened successfully.
 Setting token and publishing listen
 Stream is ready
 signalingState is "have-remote-offer"
 signalingState is "stable"
 dtlsTransportState is "new"
 pc.iceGatheringState is "gathering"
 pc.iceConnectionState is "checking"
 ICE Candidate: {"candidate":"candidate:34xxxxxxxx 1 udp 2122194687 1xx.xxx.x.x 6xxxx typ host generation 0 ufrag i+s4 network-id 1 network-cost 10","sdpMid":"audio","sdpMLineIndex":0,"usernameFragment":"i+s4"}
 ICE Candidate: {"candidate":"candidate:3x9xxxxxx 1 udp 2xxxxxxxxxxx 2xxx:xxxx:xxxx:xx:xxxx:xxxx:xxxx:xxxx 5xxxx typ host generation 0 ufrag i+s4 network-id 2 network-cost 10","sdpMid":"audio","sdpMLineIndex":0,"usernameFragment":"i+s4"}
 pc.connectionState is "connecting"
 ICE Candidate: {"candidate":"candidate:84xxxxxxx 1 tcp 15xxxxxxx 1xx.xxx.x.x 9 typ host tcptype active generation 0 ufrag i+s4 network-id 1 network-cost 10","sdpMid":"audio","sdpMLineIndex":0,"usernameFragment":"i+s4"}
 ICE Candidate: {"candidate":"candidate:1xxxxxxxxxx 1 tcp 15xxxxxxxx 2xxx:xxxx:xxxx:xx:xxxx:xxxx:xxxx:xxxx 9 typ host tcptype active generation 0 ufrag i+s4 network-id 2 network-cost 10","sdpMid":"audio","sdpMLineIndex":0,"usernameFragment":"i+s4"}
 pc.iceGatheringState is "complete"
 ICE Candidate: null
 dtlsTransportState is "connecting"
 pc.iceConnectionState is "connected"
 Media connection established.
 dtlsTransportState is "connected"
 pc.connectionState is "connected"
 Rejected: CAxxxxxxx
 pc.iceConnectionState is "disconnected"
 ICE liveliness check failed. May be having trouble connecting to Twilio
 ICE liveliness check failed. May be having trouble connecting to Twilio
 pc.connectionState is "disconnected"
 pc.connectionState is "failed"
 Connection with Twilio was interrupted.
```

**Software versions:**

 - [x] Browser(s): Chromium Version 118.0.5993.70
 - [x] Operating System: MacOS
 - [x] twilio.js: 4.18.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React Native 0.64.4, Expo SDK - 44, React Native Web: 0.17.1

**Comment by tejinder-sarna** [comment]
To add, this does not happen if there is a single incoming call

**Comment by charliesantos** [comment]
@tejinder-sarna can you please provide the correct SDK version you're using? I see you listed 4.18.1 but we're currently only at 2.7.x.

**Comment by tejinder-sarna** [comment]
@charliesantos I found the issue, I was using lodash.cloneDeep in my code which might have changed the correct reference to call and caused the problem. I have tried removing that and it works well :). Thank you
