### ISSUE TITLE
[BUG] Outbound call customParameters missing

### ISSUE THREAD

**Issue by amitava82** [twilio/twilio-voice.js#212]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

When an outbound call is made from browser, backend set custom parameters which I can see is being received in websocket events but the parameters are missing from call object. I'm not sure what the `invite` event either and how to listen to it. I have handler for device `incoming`, call `accept`, `ringing` but none of them have it.  

Here the websocket payload:

```
{
  "payload": {
    "callsid": "CA08a6d92b106e8fb8d3b3e7cb5687a6b5",
    "reconnect": "JDybrifTHd1bAatMRUuVOdkx/hbYOSPVwrdlS8LBRE+feY1jF2fI3dxC/MtNyNZKR7gkGoJ5M1VNbgaVlOj93R7riPJH6D8p7LdUFxKb4CxbDjUQDx8kw8NzDPBn24MtooFq/1+GiDowP9T5FpgiKvgKth228q5OhtdsyNL0hVpJRjB7wkp35HIPhL06ewZTOHqQH1O1wWP+EDITqsJCzDJsrEul8x2vzTrKiQz5",
    "parameters": {
      "Params": "contact_hash=rei2uepEdW80SsYubHD9&contact_last_name=Skype&contact_first_name=TIC&primary_phone=6366424905",
      "From": "+14086680261",
      "CallSid": "CA08a6d92b106e8fb8d3b3e7cb5687a6b5",
      "To": "client:amitava82m4gmailcom",
      "AccountSid": "ACb0b74a4cbdd4936bebeb5c78fa01f820"
    },
    "sdp": "v=0\r\no=root 1255372664 1255372664 IN IP4 172.19.95.157\r\ns=Twilio Media Gateway\r\nc=IN IP4 3.1.77.121\r\nt=0 0\r\na=group:BUNDLE audio\r\na=ice-lite\r\nm=audio 18566 RTP/SAVPF 107 0 101\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:107 opus/48000/2\r\na=fmtp:107 useinbandfec=1\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-16\r\na=ptime:20\r\na=maxptime:20\r\na=ice-ufrag:1dd10ec26cbe28bb444e84e268b790b1\r\na=ice-pwd:0360b09e1c103611676280a205105c13\r\na=candidate:H3014d79 1 UDP 2130706431 3.1.77.121 18566 typ host\r\na=candidate:H3014d79 2 UDP 2130706430 3.1.77.121 18567 typ host\r\na=end-of-candidates\r\na=connection:new\r\na=setup:actpass\r\na=fingerprint:sha-256 B9:EA:C6:1A:B1:42:3B:96:33:0F:7E:9A:91:4F:B8:75:83:4D:F4:33:28:D4:8A:76:7F:4D:68:76:9D:CC:01:83\r\na=mid:audio\r\na=msid:05b0a1b7-3aba-45f4-aa27-fdbf91316c5a 06503aab-f2dc-4e86-97ec-183671ff919a\r\na=ssrc:561589402 msid:05b0a1b7-3aba-45f4-aa27-fdbf91316c5a 06503aab-f2dc-4e86-97ec-183671ff919a\r\na=ssrc:561589402 mslabel:05b0a1b7-3aba-45f4-aa27-fdbf91316c5a\r\na=ssrc:561589402 label:06503aab-f2dc-4e86-97ec-183671ff919a\r\na=rtcp-mux\r\na=ssrc:561589402 cname:31e955ba-a80f-40e2-a832-9a20059f2016\r\na=sendrecv\r\n"
  },
  "type": "invite",
  "version": "1.6"
}
```

**Expected behavior:**

Should be able to access parameters set from server in call customParameters

**Actual behavior:**
Only From and To properties available on customParameters

**Software versions:**

 - [x] Browser(s):Firefox
 - [X] Operating System: OSX
 - [X] twilio.js: 2.7.3
 - [X] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by amitava82** [comment]
I've noticed, in info log it says `Device busy; ignoring incoming invite`

**Comment by charliesantos** [comment]
@amitava82 are you still seeing the issue where outbound call customParameters are missing? Are you able to reproduce it? Please provide a callsid so we can take a look.
Regarding `Device busy; ignoring incoming invite`, it happens when an incoming call received while another call is active. The SDK will ignore it, unless you set `allowIncomingWhileBusy` to true in the device [options](https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice#deviceoptions).

**Comment by amitava82** [comment]
@charliesantos Yes, the callsid I provided in the example, does it help? I'm having another problem, I'll be able to provide you a new one once I solve my other issue.

**Comment by amitava82** [comment]
@charliesantos Alright, I've got some more update. When I initiate the call, callsid is `CAff7fb6b98ca3ad18af23a81e8bd34d7a`. For this, I do not see any of those parameter I'm expecting. But then in the websocket I see an `invite` type with callsid `CA1befa4de82646867f742ee089d64aea7` that has all expected parameters.

**Comment by charliesantos** [comment]
@amitava82 , base on the logs your provided, the call is an "incoming" call to the SDK. Meaning, if you want to access the parameters set by the server, you need to use [call.parameters](https://www.twilio.com/docs/voice/sdks/javascript/twiliocall#callparameters) property.
On a related note, if you're making an "outgoing" call using `device.connect()` API, [call.customParameters](https://www.twilio.com/docs/voice/sdks/javascript/twiliocall#callcustomparameters) property will contain the parameters you provided in `device.connect()` API
