### ISSUE TITLE
[FEATURE] Native call holding & queueing. 

### ISSUE THREAD

**Issue by cybex-dev** [twilio/twilio-voice.js#220]
I am developing a native call "holding" feature - this ticket/issue is aimed at development considerations, potential issues or insight into this feature.

I intend this as a discussion for development.

**Describe the solution you'd like**
Customer requires the SDK to serve the purpose of a `CallKit`, as found on iOS whereby a call can be answered and:
- placed on hold, 
- swapped in-place of active call,
- merged with active call

The intended use-case is a web softphone for customer/clients to call from a web platform, merge multiple calls or in a call-centre environment to "queue" calls.

This feature provides the developer a browser client solution to call holding, as found on an Android `ConnectionService` or iOS `CallKit` implementation

**Describe alternatives you've considered**
See this discussion for further information and context, specifically adding a back backend-based solution with a [conference call](https://www.twilio.com/blog/introducing-conference-hold-html) implementation.

Several discussions/issues on StackOverflow & GitHub issues explore the above solution in more details:
- https://github.com/twilio/twilio-voice.js/issues/32
- [Place a Twilio call on hold and retrieve it later](https://stackoverflow.com/questions/19345222/place-a-twilio-call-on-hold-and-retrieve-it-later)
- [How to call, Hang up, put on hold and unhold calls using Twilio?](https://stackoverflow.com/questions/45783234/how-to-call-hang-up-put-on-hold-and-unhold-calls-using-twilio)
- [Transform a Twilio call into conference](https://stackoverflow.com/questions/69570402/transform-a-twilio-call-into-conference)

**Additional context**
Since this same functionality can be found in both native Android & iOS implementations, one would reasonably expect this to extend to the web client aswel.

(previously closed issue on [twilio-client.js](https://github.com/twilio/twilio-client.js/issues/328))

**Comment by charliesantos** [comment]
Closing this now. We're tracking this feature request internally. Please feel free to follow up if needed.
