### ISSUE TITLE
[FEATURE] - alternative for "forceAggressiveIceNomination" if setting is to be deprecated

### ISSUE THREAD

**Issue by yanniel** [twilio/twilio-voice.js#230]
**Is your feature request related to a problem? Please describe.**

We have a use-case constrained by regulation where we need to accept incoming calls on the Dialer (browser) within 3 seconds. 

We are experimenting with [forceAggressiveIceNomination](https://github.com/twilio/twilio-voice.js/blob/master/lib/twilio/device.ts#L1880) in the hope that it could reduce the call connect time.

We noticed however a comment in the source code suggesting [forceAggressiveIceNomination will be removed](https://github.com/twilio/twilio-voice.js/blob/master/lib/twilio/device.ts#L1025). 

```
 // TODO(csantos): Remove forceAggressiveIceNomination option in 3.x
 forceAggressiveIceNomination: this._options.forceAggressiveIceNomination,
```

**Describe the solution you'd like**

We would like an alternative to `forceAggressiveIceNomination` if it is to be deprecated. Short of that, could you explain the rationale for removing/deprecating this setting?

**Describe alternatives you've considered**

We have considered using [RTCPeerConnection#icecandidatepoolsize](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection#icecandidatepoolsize) to minimize the time it takes to establish connectivity for incoming calls; but in some cases we are running into this bug: https://github.com/twilio/twilio-voice.js/issues/67#issuecomment-1866325786

Reference from spec and code sample just below.

> 
> [3.5.4. ](https://www.rfc-editor.org/rfc/rfc8829#section-3.5.4)[ICE Candidate Pool](https://www.rfc-editor.org/rfc/rfc8829#name-ice-candidate-pool)
> 
> One example of where this concept is useful is an application that expects an incoming call at some point in the future, and wants to minimize the time it takes to establish connectivity, to avoid clipping of initial media. By pre-gathering candidates into the pool, it can exchange and start sending connectivity checks from these candidates almost immediately upon receipt of a call.

```
import { Device } from '@twilio/voice-sdk'

const callAcceptOptions = {
      rtcConstraints: {
        audio: true
      },
      rtcConfiguration: {
        iceCandidatePoolSize: 1
      }
};

const device = new Device(token, {
      codecPreferences: ["opus", "pcmu"],
      dscp: true,
});

device.register();

device.on(Device.EventName.Incoming, (call) => {
      call.accept(callAcceptOptions); 
});
```

**Additional context**
N/A

**Comment by charliesantos** [comment]
Thanks for reaching out @yanniel . forceAggressiveIceNomination will be removed in a major version bump and icecandidatepoolsize is being considered. However, this won't happen soon so feel free to continue using forceAggressiveIceNomination if it works with your setup. Regarding https://github.com/twilio/twilio-voice.js/issues/67#issuecomment-1866325786, it is in our radar and it will be fixed in the near future.

**Comment by yanniel** [comment]
Thanks @charliesantos .

Could you please clarify this statement? -> "icecandidatepoolsize is being considered"

Is "icecandidatepoolsize" ready to be used as of [version 2.10.0 ](https://github.com/twilio/twilio-voice.js/releases/tag/2.10.0) or support for it will be introduced later? I was under the impression this feature was ready to be used as shown below:

```
import { Device } from '@twilio/voice-sdk'

const callAcceptOptions = {
      rtcConfiguration: {
        iceCandidatePoolSize: 1
      }
};

const device = new Device(token, {
      codecPreferences: ["opus", "pcmu"],
      dscp: true,
});

device.register();

device.on(Device.EventName.Incoming, (call) => {
      call.accept(callAcceptOptions); 
});
```

**Comment by charliesantos** [comment]
@yanniel Thanks for the follow up! "icecandidatepoolsize is being considered" meaning, we will make sure this config will achieve the same behavior as forceAggressiveIceNomination before removing it.
Theoretically you should be able to start using/testing iceCandidatePoolSize since the SDK allows for a rtcConfiguration to be passed in.

**Comment by charliesantos** [comment]
Hey @yanniel thanks again for the collaboration on this topic. I will close this now since we don't have any immediate action on our end. Feel free to follow up if necessary.
