### ISSUE TITLE
Custom job to export voice call logs for a day range with startDate=endDate, i.e. one day, triggers webhook 4 times

### ISSUE THREAD

**Issue by SINGHPRT** [twilio/twilio-voice.js#246]
We are using com.twilio.rest.bulkexports.v1.export.ExportCustomJob  to export Voice call logs for a given day as follows:

ExportCustomJob exportCustomJob = ExportCustomJob.creator(
    						"Calls",
    		                "2024-02-10",
    		                "2024-02-10",
    		                "10 feb voice log export")    		           
    		            .setWebhookMethod("POST")
    		            .setWebhookUrl(webHookURL)
    		            .create();

We find that our webhook url is getting hit with the same form data and status=completed 4 times for each such job completed.
This is causing re-run of webhook logic like loading duplicate logs in our system.
Please let us know what is causing this and how can we fix it?

**Comment by charliesantos** [comment]
Hi @SINGHPRT . Thanks for submitting. This repository is for the Twilio Programmable Voice JavaScript SDK. Can you please submit a support ticket using your Twilio account? Our support team should be able to route your ticket to the correct team.
