### ISSUE TITLE
[BUG] Switching microphone device from system does not work on the first instance

### ISSUE THREAD

**Issue by varunm0503** [twilio/twilio-voice.js#256]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Adding a reference from code in audioHelper.ts file

```js
if (deviceChanged || lostDeviceIds.length) {
            // Force a new gUM in case the underlying tracks of the active stream have changed. One
            //   reason this might happen is when `default` is selected and set to a USB device,
            //   then that device is unplugged or plugged back in. We can't check for the 'ended'
            //   event or readyState because it is asynchronous and may take upwards of 5 seconds,
            //   in my testing. (rrowland)
            if (this.inputDevice !== null && this.inputDevice.deviceId === 'default') {
                this._log.warn("Calling getUserMedia after device change to ensure that the           tracks of the active device (default) have not gone stale.");
                this._setInputDevice(this.inputDevice.deviceId, true);
            }
            this._log.debug('#deviceChange', lostActiveDevices);
            this.emit('deviceChange', lostActiveDevices);
        }
```

**Suggested code fix**

```js
if (deviceChanged || lostDeviceIds.length) {
            // Force a new gUM in case the underlying tracks of the active stream have changed. One
            //   reason this might happen is when `default` is selected and set to a USB device,
            //   then that device is unplugged or plugged back in. We can't check for the 'ended'
            //   event or readyState because it is asynchronous and may take upwards of 5 seconds,
            //   in my testing. (rrowland)
            if ((this.inputDevice === null && this.availableInputDevices.get("default")) || (this.inputDevice && this.inputDevice.deviceId === 'default')) {
                this._log.warn("Calling getUserMedia after device change to ensure that the           tracks of the active device (default) have not gone stale.");
                this._setInputDevice('default', true);
            }
            this._log.debug('#deviceChange', lostActiveDevices);
            this.emit('deviceChange', lostActiveDevices);
        }
```

**Expected behavior:**

When we are switching microphone device from our system (i.e changing my default device from one inbuilt device to bluetooth device), the voice call should start taking input stream from new default device. 

**Actual behavior:**
When we are switching microphone device from our system (i.e changing my default device from one inbuilt device to bluetooth device), input stream becomes stale and voice cannot be heard by other party on call. 

Attached a code update that may be needed to fix this issue. The issue does not happen once setDevices is manually called in twilio sdk api. Once we call setDevices, inputDevice is set and from then on switching microphone device from system is no longer an issue. 
 
`this.inputDevice === null || (this.inputDevice !== null && this.inputDevice.deviceId === 'default'`

**Software versions:**

 - [x] Browser(s): Chrome v124.0.6367.62
 - [x] Operating System: MacOS Monterey
 - [x] twilio.js: 2.10.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by charliesantos** [comment]
Thanks for your contribution @varunm0503 . I included this in a separate PR along with other fixes https://github.com/twilio/twilio-voice.js/pull/270
