### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'info')

### ISSUE THREAD

**Issue by m-bp** [twilio/twilio-voice.js#263]
**Code to reproduce the issue:**

I am unable to reproduce this issue locally but I have the following code:

```typescript
device.on('unregistered', () => {
  device.disconnectAll()
  device.destroy()
})
```

Sometimes when one of my users gets disconnected the following error will show up:

> TypeError: Cannot read properties of null (reading 'info')

Coming from [here](https://github.com/twilio/twilio-voice.js/blob/master/lib/twilio/device.ts#L1627).

Seconds after the device has been destroyed.

It makes perfect sense. The promise is started right before being destroyed and by the time it's resolved the object is null.

**Comment by charliesantos** [comment]
Thanks for submitting @m-bp . After this happens, do you see any issues on future calls? Or this the error benign?

**Comment by m-bp** [comment]
It's usually just this error and nothing seems to break. I cannot confirm 100%, however, as I cannot reproduce it myself.

**Comment by charliesantos** [comment]
Thanks @m-bp . I'll close this for now but I'll put it under our radar as we cannot do anything right now. Feel free to follow up if you find any new information.

**Comment by m-bp** [comment]
@charliesantos I don't see why it wouldn't be possible to add a couple of null checks inside the promises' callbacks to prevent this error from happening?

**Comment by charliesantos** [comment]
We definitely can @m-bp . I can submit an internal ticket to track this.
