### ISSUE TITLE
call.ignore() not working in this new version

### ISSUE THREAD

**Issue by riteshsainju** [twilio/twilio-voice.js#34]
`call.ignore()
`
This method was supposed to the stop incoming sound but its not working after migrating from  1.X version to 2.x version.

**Comment by riteshsainju** [comment]
Any update for this issue?

**Comment by skylord123** [comment]
Same problem here. `call.ignore()` does not work and seems to do nothing.

**Comment by skylord123** [comment]
As a workaround until this gets fixed (a bit sad there hasn't been any activity on this at all) you can do this:

```
device._soundcache.get(Device.SoundName.Incoming).stop();
```

I added this after my `call.ignore()` to stop the ringing sound manually.

**Comment by ryan-rowland** [comment]
Thanks for bringing this to our attention. It seems some logic was unintentionally removed as part of the transition. I've cut an internal ticket to fix this.

**Comment by charliesantos** [comment]
Should be fixed as of 2.1.1
