### ISSUE TITLE
SDK does not support Typescript 4.4 and therefore @angular/cli 13.0.0

### ISSUE THREAD

**Issue by InnovativeUS** [twilio/twilio-voice.js#44]
- [x ] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Should not fail compile. DOMError should be removed - it has been deprecated (https://developer.mozilla.org/en-US/docs/Web/API/DOMError).

**Actual behavior:**

With angular 13.0.0 the minimum typescript version is 4.4. Typescript 4.4 removed DOMError (https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029)

Therefore when trying to compile with Angular the following error is displayed.

Error: node_modules/@twilio/voice-sdk/es5/twilio/preflight/preflight.d.ts:52:38 - error TS2304: Cannot find name 'DOMError'.

52     failedEvent(error: TwilioError | DOMError): void;
TODO

**Software versions:**

 - [X] Browser(s): Chrome
 - [x] Operating System: MacOS
 - [X] twilio.js: 2.0.1
 - [X] Third-party libraries (e.g., Angular, React, etc.): Angular 13, Typescript 4.4

**Comment by sebastianvog** [comment]
fwiw, the workaround suggested, didn't seem to work on my angular 13 project ? or was that meant to be done on the library itself?

**Comment by ryan-rowland** [comment]
Thanks for bringing this to our attention. I've added an internal ticket for this issue and plan to begin investigation sometime this week.

**Comment by shyamal890** [comment]
@ryan-rowland is there a temporary fix to this issue that we can do in our Angular app?

**Comment by charliesantos** [comment]
Should be fixed as of 2.1.1

**Comment by AravindJo-kore** [comment]
any resolution yet ?

**Comment by charliesantos** [comment]
@AravindJo-kore please try on latest version.
