### ISSUE TITLE
[FEATURE] Call Warning Events

### ISSUE THREAD

**Issue by coldboot-damikez** [twilio/twilio-voice.js#47]
**Is your feature request related to a problem? Please describe.**
Please implement the warning events similar to what we had in the twilio-client SDK

**Comment by ryan-rowland** [comment]
@coldboot-damikez could you please elaborate? The `Call.on('warning')` and `Call.on('warning-cleared')` events are both still present on this version of the SDK.

**Comment by coldboot-damikez** [comment]
Ok. I checked on the SDK documentation at that time and I didn't see anything referring to the `Call.on("warning")` method. I will close this issue now. Thanks!
