### ISSUE TITLE
[BUG] Vite and Vue - Device.prototype.connect isn't invoked.

### ISSUE THREAD

**Issue by dziardziel-acaisoft** [twilio/twilio-voice.js#52]
- [ X ] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [ X ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ X ] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [ X ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

I'm able to establish a call

**Actual behavior:**

Nothing happens. No error is thrown.

I'm pretty sure that this error comes from Vite and @twilio/voice-sdk unable to work together.

My code works perfectly when using vue-cli-service instead of vite, however when I paste the exact same code into vite project, it fails silently (without throwing any errors) at the line:
```
const params = { To: this.currentNumber };

console.log("BEFORE") // This console.log shows in browser devTools.
this.twilioCall = await this.twilioDevice.connect({ params });
console.log("AFTER") // This console.log won't show in browser devTools.
```

I've tried to add some console.logs into `node_modules/@twilio/voice-sdk/es5/twilio/device.js -> Device.prototype.connect`, but even if I try to add it before the first line of the function, it won't print.

**Software versions:**

 - [x] Browser(s): Chrome, Brave, Firefox,
 - [x] Operating System: macOS 12.01,
 - [x] Vite 2.6.14,
 - [x] Vue 3.2.22

**Comment by ryan-rowland** [comment]
Hi @dziardziel-acaisoft, we don't specifically test usage in conjunction with Vue or Vite, but we are currently investigating #55 and if the root cause is the same this should hopefully address your issue as well. Please watch #55 for updates!
