### ISSUE TITLE
How to mute the remote Audio with call.getRemoteStream() ?

### ISSUE THREAD

**Issue by phamkythanh** [twilio/twilio-voice.js#54]
I can access the remote audio stream from this method `call.getRemoteStream()` (https://www.twilio.com/docs/voice/sdks/javascript/twiliocall#callgetlocalstream) but don't know how to mute/unmute the audio. Anyone know how should we use the MediaStream object for this case? Attached is the console.log for the object from `call.getRemoteStream()`
<img width="947" alt="Screen Shot 2021-12-09 at 4 48 51 PM" src="https://user-images.githubusercontent.com/11988398/145373397-fe2065b3-3873-4dc7-8275-f3177323c7f3.png">

**Comment by JonKnowlesThrasys** [comment]
Toggling the `enabled` property on the remote media stream audio tracks works for me. Something like this: 
```js 
const audioTracks = remoteStream.getAudioTracks();
audioTracks.forEach((track) => {
  track.enabled = !isMuted;
});
```

**Comment by ryan-rowland** [comment]
Hi @phamkythanh, hopefully @JonKnowlesThrasys's answer was helpful for you. I'll be closing this as it's not related to any SDK functionality.
