### ISSUE TITLE
[BUG] Device is registered and can make outgoing calls but can not receive incoming calls.

### ISSUE THREAD

**Issue by eglove** [twilio/twilio-voice.js#59]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```ts
const device = new Device(voiceToken, {
  logLevel: 1,
});

await device.register();

device.on('incoming', (call: Call) => {
  handleCallStateChange(call);
  // Or some other stuff
});
```

**Expected behavior:**

Receive incoming calls, see something in the console for debug, or be able to console log something on the incoming event. Support has asked me to verify that I'm using Device.setup() which is a method of twilio-client. Not @twilio/voice-sdk. twilio-client no longer works with my project.

**Actual behavior:**

When attempting to make the call, it immediately hangs up, nothing is logged to Twilio Console. I can, however, make outgoing calls.

Logs for outgoing call:

1. Setting up VSP
1. Initializing transport backoff using config:  {factor: 2, initialDelay: 100, maxDelay: 20000, randomisationFactor: 0.4}
1. WSTransport.open() called...
1. Attempting to connect...
1. Closing and cleaning up WebSocket...
1. No WebSocket to clean up.
1. WebSocket opened successfully.
1. Setting token and publishing listen
1. Stream is ready
1. signalingState is "have-local-offer"
1. dtlsTransportState is "new"
1. pc.iceGatheringState is "gathering"
1. ICE Candidate: {"candidate":"candidate:2047522363 1 udp 2122260223 10.0.24.180 64237 typ host generation 0 ufrag a0X0 network-id 1","sdpMid":"0","sdpMLineIndex":0}
1. ICE Candidate: {"candidate":"candidate:881412811 1 tcp 1518280447 10.0.24.180 9 typ host tcptype active generation 0 ufrag a0X0 network-id 1","sdpMid":"0","sdpMLineIndex":0}
1. pc.iceGatheringState is "complete"
1. ICE Candidate: null
1. pc.iceConnectionState is "checking"
1. signalingState is "stable"
1. pc.connectionState is "connecting"
1. dtlsTransportState is "connecting"
1. pc.iceConnectionState is "connected"
1. Media connection established.
1. dtlsTransportState is "connected"
1. pc.connectionState is "connected"
1. Disconnecting...
dtlsTransportState is "closed"

**Software versions:**

 - [x] Browser(s): Chrome 96.0.4664.110
 - [x] Operating System: Windows 10
 - [x] twilio.js: twilio 3.70.0, @twilio/voice-sdk 2.0.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): React 17.0.2, Next 12.0.1

**Comment by ryan-rowland** [comment]
Hi @eglove, for technical support for issues such as this please go through our ticketing system in your Twilio console, where our Technical Support team can give you their full attention. We're not able to provide the same level of support here on the GitHub issues as the engineering team.
