### ISSUE TITLE
[BUG] Support node LTS

### ISSUE THREAD

**Issue by dcustodio** [twilio/twilio-voice.js#60]
As I was trying to install the `@twilio/voice-sdk` I got the following error:

> error @twilio/voice-sdk@2.1.0: The engine "node" is incompatible with this module. Expected version "12". Got "16.6.2"

It would be nice if this package would work with the latest node LTS (v16).

Keep up the good work!

**Comment by lanlin** [comment]
```shell
error @twilio/voice-sdk@2.1.0: The engine "node" is incompatible with this module. Expected version "12". Got "17.2.0"
```

**Comment by lanlin** [comment]
```shell
 @twilio/voice-sdk > @twilio/audioplayer > babel-runtime > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-j
```

**Comment by vekerdyb** [comment]
This seems like a regression as `v2.0.1` installs fine on my version of node (14), but `v2.1.0` does not.

**Comment by theWebKeyGuy** [comment]
I would also appreciate it if this was updated to the latest node. :)

**Comment by benmccallum** [comment]
Probably worth mentioning that v12 also reaches EOL in a couple of months. 
https://nodejs.org/en/about/releases/

**Comment by jaymdq** [comment]
Is there any ETA for this fix?

**Comment by ryan-rowland** [comment]
We've added an internal ticket for this and I aim to start processing it this week. Thanks for bringing this up and pinging us again!

**Comment by vekerdyb** [comment]
Thanks for merging the fix @ryan-rowland! 
Do you know when it can be released as a new version on NPM?

**Comment by ryan-rowland** [comment]
I'm re-opening this issue for visibility until the fix actually makes it into the release -- sorry about that. Expecting the release early next week.

**Comment by vekerdyb** [comment]
Hey @ryan-rowland sorry for keep pushing for this, but do you have an idea when this would be released? 
Thanks!

**Comment by laurel-taylor** [comment]
Also wondering if this is still slated for release soon. Node 12 EOL is coming up 😬 thanks!

**Comment by benmccallum** [comment]
Issue should be renamed `[BUG] ...` as per the tag. Might help it get the attention it needs.

**Comment by dcustodio** [comment]
The version [2.1.1](https://github.com/twilio/twilio-voice.js/releases/tag/2.1.1) is already published and fixes this issue.
