### ISSUE TITLE
[FEATURE] Limit maximum retry time for device.connect()

### ISSUE THREAD

**Issue by artemzarutskiy** [twilio/twilio-voice.js#63]
**Is your feature request related to a problem? Please describe.**
If `device.connect()` is called when there is no internet connection available, it will keep attempting to create a `Call` for a long time and, once the internet connection is back up, it will create it. This creates an unpredictable behavior in the following scenario:

1. User opens a page, Twilio device gets initiated
2. Wi-Fi disconnects
3. User tries to initiate an outbound call with no success
4. User steps away from the computer
5. Wi-Fi reconnects after some time
6. `Call` is created without user being aware/present

**Describe the solution you'd like**
Add `maxCallInitiationTimeoutMs` option to `DeviceOptions`, which would cancel an attempt to create a `Call` after the set number of milliseconds. 

**Describe alternatives you've considered**
For now, we measure the time between calling `device.connect()` and the callback firing, and if it's over 5 seconds, calling  `device.disconnectAll()`:
```
const callInitiatedAt = new Date();
device.connect({params: {To: phoneNumber}}).then(call => {
    if (new Date() - callInitiatedAt > 5000)
        device.disconnectAll();
});
```
This is not ideal because it still creates a `Call` for a brief moment and plays a sound.

**Comment by ryan-rowland** [comment]
Thanks for bringing up this edge case, this isn't something we've been testing for. We will discuss your suggested solution and brainstorm some others internally!

**Comment by mhuynh5757** [comment]
Hi @artemzarutskiy, the team is prioritizing tickets and this one has gone a bit stale. We don't have anything planned for this in the near future but we will update this ticket if that changes.
