### ISSUE TITLE
`reject` doc update 

### ISSUE THREAD

**Issue by honkimi** [twilio/twilio-voice.js#65]
https://twilio.github.io/twilio-voice.js/classes/voice.call.html#rejectevent

x call.on('reject', call => { })
o call.on('reject' () => { })

I hope it'll be updated soon.
Thanks!

**Comment by ryan-rowland** [comment]
Thanks for pointing this out! I've opened a PR to fix this documentation error.

**Comment by kbagchiGWC** [comment]
Closing this as it is fixed by https://github.com/twilio/twilio-voice.js/pull/66.
