### ISSUE TITLE
[BUG] TypeError: Failed to construct 'RTCPeerConnection': Malformed constraints object.

### ISSUE THREAD

**Issue by thexeos** [twilio/twilio-voice.js#67]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
import { Device } from '@twilio/voice-sdk'

const device = new Device(token, {
  logLevel: 'debug' /* does not work, but that's unrelated, and { debug: true } is not declared in TS */
})

device.connect({
  rtcConfiguration: {
    iceTransportPolicy: 'all',
    iceServers: [{ urls: 'stun:global.stun.twilio.com:3478?transport=udp' }]
  },
  rtcConstraints: {
    audio: true /* as per TS interface - boolean | MediaTrackConstraints */
  }
})
```

**Expected behavior:**

Should work.

**Actual behavior:**

TypeError: Failed to construct 'RTCPeerConnection': Malformed constraints object.

![msedge_WrbcTkg155](https://user-images.githubusercontent.com/2260539/150237829-54b74c5f-2092-4a83-a9a0-76418e9767d5.png)

These are the parameters that were passed (servers are actual Twilio's TURN servers, but any would work):

![msedge_ZifntT8ju0](https://user-images.githubusercontent.com/2260539/150237879-e9ddb3b7-a005-4cd3-be6f-1639ed650f70.jpg)

![msedge_8Cgmy00Xzp](https://user-images.githubusercontent.com/2260539/150237949-dff31949-a512-4c65-adf0-53ada18ddfa0.jpg)

**Software versions:**

 - [x] Browser(s): Edge 97.0.1072.62
 - [x] Operating System: Windows 10
 - [x] twilio.js: 2.1.0

Now, the user-side "solution" is not passing anything in `rtcConstraints`. The library-side solution is correctly handling the received `rtcConstraints` across different WebRTC versions. The [current version](https://w3c.github.io/webrtc-pc/#dom-peerconnection) defines only one parameter passed to RTCPeerConnection constructor. Anything else is legacy/compatibility mode, which requires special treatment.

**Comment by Oylex** [comment]
I have the same issue, removing the constraints worked, but is not ideal, I'll watch this issue.

**Comment by mhuynh5757** [comment]
Thanks for filing this issue @thexeos , we have filed an internal issue and will look into this.

**Comment by GuilhermeLessa** [comment]
The same bug here, I just can make browser client calls from Edge to Firefox. Any other browsers or direction don't work.

**Comment by kamalbennani** [comment]
@charliesantos any news regarding this issue?
It seems that the RTCPC doesn't actually depend on "rtcConstraints", is it a leftover or a SHIM legacy?

**Comment by charliesantos** [comment]
Hi @kamalbennani , thanks for the ping! We have no updates yet regarding this issue. I updated our internal ticket and it will be considered in the next release.

**Comment by alawimartins** [comment]
Hello @charliesantos , do you know when this issue will be fixed? We are still having the problem as @kamalbennani described.
Thanks

**Comment by yanniel** [comment]
```

import { Device } from '@twilio/voice-sdk'

const callAcceptOptions = {
      rtcConstraints: {
        audio: true
      },
      rtcConfiguration: {
        iceCandidatePoolSize: 1
      }
};

const device = new Device(token, {
      codecPreferences: ["opus", "pcmu"],
      dscp: true,
});

device.register();

device.on(Device.EventName.Incoming, (call) => {
      call.accept(callAcceptOptions); 
});
```
The code above also triggers the error; but it only does so if the user is using an outdated version of Chrome. So far we have seen the error in the versions below:

- Chrome 103.0.0.0
- Chrome 98.0.4758.102
- Chrome 95.0.4638.74
- Chrome 93.0.4577.107
- Chrome  92.0.4515.131
- Chrome 78.0.3904.130

**Solutions/workarounds:**

- Upgrading to Chrome 120.0.0.0 solves the issue.
- If `rtcConstraints` is removed from `callAcceptOptions` then the error disappears and the above code works on all version of Chrome.

**Comment by charliesantos** [comment]
Fixed in https://github.com/twilio/twilio-voice.js/pull/238
Watch out for the next release.
