### ISSUE TITLE
The old twilio-client package works on node 14, but the new @twilio/voice-sdk package can't be installed [BUG]

### ISSUE THREAD

**Issue by seth-church** [twilio/twilio-voice.js#68]
After upgrading to node 14, I tried switching from the old twilio-client package to the new @twilio/voice-sdk package as recommended. On install, npm produced this message:
npm ERR! notsup Unsupported engine for @twilio/voice-sdk@2.1.0: wanted: {"node":"12"} (current: {"node":"14.18.3","npm":"6.14.15"})

So we're stuck with the twilio-client package. Please help! Note that the twilio-client package can be installed on node 14 and that phone calls work fine with this package. Not sure what the new @twilio/voice-sdk package is afraid of. Can you please test the new package with node 14 and open it up for use on this node version?

Note that node 12 will not be maintained after April 2022. See: https://nodejs.org/en/about/releases/

**Comment by ryan-rowland** [comment]
This has been fixed in dev and will be released soon! Please follow #60 for updates
