### ISSUE TITLE
[FEATURE] Modernize the code?

### ISSUE THREAD

**Issue by rationalthinker1** [twilio/twilio-voice.js#72]
**Is your feature request related to a problem? Please describe.**
Yes, I cannot use Vite because the code is not updated

**Describe the solution you'd like**
a modernize codebase, with `import`, `async`, replacing `xmlhttprequest` with `fetch` etc...

**Comment by aaroncsolomon** [comment]
Bump here^ - there are numerous issues across the codebase ranging from incompatibility with Node 16 to lack of polyfill handling out of the box to use of xmlhttprequest (which causes issues with bundling) - Twilio needs to get devs seriously involved with making the twilio-voice client useable because it'd be highly useful for lots of us if it worked but right now it's a burden to get up and running

**Comment by pgib** [comment]
Yeah, went to import this package just now only to discover the latest release doesn't support anything other that node 12. Surprising to say the least!

**Comment by pgib** [comment]
> Node 12 is entering End of Life in about 2 months. Requiring Node 12 makes using this a non-starter. Are there any timelines in place for when we can expect an update?

I'm using the Github repo as my package source in the meantime, and so far this is working okay. Would be good to have some official response though.

**Comment by charliesantos** [comment]
Hey everyone, apologies for the inconvenience. We are actively working on updating the codebase to make sure it's compatible with the latest tools. We have a few things in mind such as updating node version and some build tools. To help us address your concerns, can you please let us know what "modernize" mean from your perspective? We want to make sure our plan aligns with your expectations. Reading the comments here, I see the following:

- support the latest node version
- replacing `xmlhttprequest` with `fetch` - please let us know how this affects you
- modernize codebase, with `import`, `async` - please let us know what this means to you
- anything else?

As always, thank you for your contributions!

**Comment by charliesantos** [comment]
Hey everyone, we made a few improvements please check this out https://github.com/twilio/twilio-voice.js/issues/55#issuecomment-1571122310
Other items mentioned in the [previous comment](https://github.com/twilio/twilio-voice.js/issues/72#issuecomment-1487308784) will be addressed soon. Please stay tuned!

**Comment by charliesantos** [comment]
We made more improvements and the SDK now supports most of the items mentioned in this ticket. Please see [changelog](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md#260-in-progress) for details. You can try these now in [2.6.0-rc2](https://github.com/twilio/twilio-voice.js/releases/tag/2.6.0-rc2).

**Comment by charliesantos** [comment]
We just released 2.7.0 which supports ESM on certain frameworks. This is the last item that was needed to be addressed in this ticket. Thank you everyone for your contributions and please feel free to reach out again if necessary.
