### ISSUE TITLE
[BUG] twilioError.ts:7 Uncaught TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by rationalthinker1** [twilio/twilio-voice.js#76]
- [X] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Software versions:**

 - [X] Browser(s): Chrome
 - [X] Operating System: Windows
 - [X] twilio.js: 2.1.0
 - [X] Third-party libraries (e.g., Angular, React, etc.): Vite

I am using Vite as a bundler. Out of the hundreds of packages that my application is using, only Twilio has this error. 

![image](https://user-images.githubusercontent.com/1825003/152900088-e3584747-2c1c-455a-b5b5-8eb7f53670e4.png)

`twilioError.ts:7 Uncaught TypeError: Object prototype may only be an Object or null: undefined`

I went through many hoops to get twilio working with Vite in the first place.

**Comment by mhuynh5757** [comment]
Thanks @rationalthinker1 , we'll look into supporting Vite. I've filed an internal ticket for this.

**Comment by charliesantos** [comment]
@rationalthinker1 are you still seeing this error?

**Comment by charliesantos** [comment]
Thanks @rationalthinker1 for providing your workaround. I submitted an internal ticket to properly address this.

**Comment by charliesantos** [comment]
This should be fixed now. Please see details here
https://github.com/twilio/twilio-voice.js/issues/55#issuecomment-1571122310
