### ISSUE TITLE
[BUG] Error on device connect

### ISSUE THREAD

**Issue by spintokha** [twilio/twilio-voice.js#81]
Hello,  someone knows why occurring this error?

**Software versions:**

 - Browser(s): Chrome
 - Operating System: Linux(Ubuntu)
 - twilio.js: 2.0.0
 - Third-party libraries: Vue
 
![image](https://user-images.githubusercontent.com/10213459/154820796-a6f450a2-582f-4bd1-ac9c-140feb058430.png)

![image](https://user-images.githubusercontent.com/10213459/154820761-e7bd122d-4786-4f9d-921a-03fd1c4951fd.png)

**Comment by charliesantos** [comment]
@spintokha you closed this issue soon after you submitted it. Can you please let us know what was wrong?
