### ISSUE TITLE
[BUG] _OnAnswer handler not being cleaned up in _cleanupEventListeners

### ISSUE THREAD

**Issue by scottwthompson** [twilio/twilio-voice.js#87]
- [x ] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

`_OnAnswer` handler not being cleaned up in `_cleanupEventListeners`

Noticed in my logs 
![image](https://user-images.githubusercontent.com/9572113/163460766-0cc53e58-ebad-4f59-91e7-879dfc6354d4.png)

I think this PR here: https://github.com/twilio/twilio-voice.js/pull/42 introduced the regression where your rebinding `_onAnswer` on every `accept` call but the `this._pstream.removeListener('answer', this._onAnswer)` call is now unsuccessful.

**Comment by bradleyy1012** [comment]
Same, glad to see I wasn't the only one with this issue.

**Comment by awwsnappitsrob24** [comment]
Does anyone have any updates on this?

**Comment by amrictor** [comment]
Waiting eagerly for a fix on this!

**Comment by bradleyy1012** [comment]
I'm not sure if this will cause any unexpected side effects, but could this be the solution?
<img width="1229" alt="Screen Shot 2022-04-26 at 2 43 53 PM" src="https://user-images.githubusercontent.com/4410719/165389055-b7541af2-4a1d-4bae-9631-89d05521495a.png">

**Comment by katie-bowman** [comment]
I have also experienced this bug, is there any update on this issue?

**Comment by mhuynh5757** [comment]
Hi all, thanks for bringing this one to the team's attention. We have filed an internal ticket to track this.

**Comment by kamalbennani** [comment]
Hi @mhuynh5757 the fix should be very straightforward here by just turning the `_onAsnwer` instance method to an arrow function, isn't it? 
Do you want me to pull up a PR for it?

**Comment by mhuynh5757** [comment]
Hi @kamalbennani, thanks for the solution, but unfortunately that might not work due to the possibility of multiple `answer` events since we now have call reconnection logic, and using an arrow function means we won't be able to unbind properly.

**Comment by kamalbennani** [comment]
I misread the situation then 🤔

**Comment by charliesantos** [comment]
@bradleyy1012 's suggestion is correct. We will include the fix for this as part of https://github.com/twilio/twilio-voice.js/issues/145

**Comment by bradleyy1012** [comment]
> @bradleyy1012 's suggestion is correct. We will include the fix for this as part of #145

Great to hear, thank you! Credit goes to @amrictor.

**Comment by charliesantos** [comment]
Should be fixed in 2.4.0
