### ISSUE TITLE
[BUG] Input and output audio goes silent in iOS Safari / WebKit 15.4 +

### ISSUE THREAD

**Issue by ostap0207** [twilio/twilio-voice.js#91]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

When starting a call in iOS Safari 15.4+ audio sometimes gets broken/silenced in both directions. It does not happen every time and requires some time to reproduce. 

In about 20 seconds after the error is thrown in the console: `A MediaStreamTrack ended due to a capture failure`.

We have filed an internal ticket in Twilio `8525040`, but also posting it here for visibility.

**Code to reproduce the issue:**

To reproduce the issue we used Twilio QuickStart and to speed up the reproduction we did:
1. Start a call immediately on page load
2. Added the code to detect the issue using input and output levels
3. Wrap the QuickStart in iFrame and reload the iFrame when the issue was not detected after some time.

Without these changes the issue can also be reproduced, just requires more manual actions, as the issue does not happen every time.

We have shared this modified QuickStart in the internal ticket, the ticket also includes debug and HAR logs. 
Here is the same code without credentials for the reference: https://github.com/ostap0207/safari-twilio/blob/master/public/quickstartv2.js

**Expected behavior:**

Audio works both ways.

**Actual behavior:**

Audio stream exists and the call is ongoing, however, there is no sounds for input and output audio.
This can be seen by using `sample` event: `audioInputLevel` and `packetsSent` are 0. 
After 20 seconds after sound loss "A MediaStreamTrack ended due to a capture failure" appears in the console.

We understand that this could be an issue with Safari, however, we tried to reproduce it using WebRTC samples https://webrtc.github.io/samples/src/content/getusermedia/audio/, but weren't able to.

**Software versions:**

 - [x] Browser(s): iOS Safari 15.4, but also other WebKit based browsers in iPhone (Chrome, FF, etc)
 - [x] Operating System: iOS
 - [x] twilio.js: v1, v2

**Comment by charliesantos** [comment]
@ostap0207 this is due to a webkit bug https://bugs.webkit.org/show_bug.cgi?id=221192
I'm watching the webkit ticket and we can close this issue since we don't have any further action item. But feel free to follow up if needed.
