### ISSUE TITLE
[BUG] `device.calls` is always an empty array

### ISSUE THREAD

**Issue by francoisl** [twilio/twilio-voice.js#96]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
const device = new Device(token);

// Make an ougoing call
device.connect({ params: { To: phoneNumber } } );

console.log(device.calls);

// Prints: 
// []
```

The issue is also reproducible when using await:
```js
await device.connect({ params: { To: phoneNumber } } );

console.log(device.calls);

// Prints: 
// []
```

**Expected behavior:**
As stated in the [documentation](https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice#devicecalls), `device.calls` should contain an instance of a `Call`, representing the outgoing call

```js
console.log(device.calls);
// [Call]
```

**Actual behavior:**

`device.calls` is always an empty array.

It appears that the [`connect`](https://github.com/twilio/twilio-voice.js/blob/e9f6c4f77889d/lib/twilio/device.ts#L553-L573) function never adds the new `activeCall` to its internal `this._calls` list.

**Software versions:**

 - [x] Browser(s): Chrome 102.0.5005.115
 - [x] Operating System: MacOS Monterey 12.4
 - [x] twilio.js: 2.1.1

**Comment by mhuynh5757** [comment]
Hi @francoisl, this is expected behavior in the `2.x` versions of the SDK (changed from `1.x`) such that `device.activeCall` is no longer part of the `device.calls` array member. Please see the updated documentation: https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice#devicecalls

**Comment by waynebrantley** [comment]
@mhuynh5757 I am not following.  The link you sent says that 'calls' is a list of calls the device instance is maintaining.   If a call is in progress it seems that would be in the calls array - as it is maintaining it.

What else would be in the calls array?
