### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'createOffer')

### ISSUE THREAD

**Issue by wjlroe** [twilio/twilio-voice.js#99]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Not raising exceptions due to calling `createOffer` on a `null` value.

**Actual behavior:**

Periodically (but quite rarely), we get this exception raised by the voice-sdk:

    TypeError: Cannot read properties of null (reading 'createOffer')

Here is the backtrace:

```
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/rtc/rtcpc.js:81:in createOffer
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/rtc/peerconnection.js:829:in createOffer
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/call.js:420:in iceRestart
webpack://[name]/./node_modules/events/events.js:153:in ReflectApply
webpack://[name]/./node_modules/backoff/lib/backoff.js:53:in emit
```

**Software versions:**

 - Browser(s): Chrome
 - Operating System: ChromeOS
 - twilio.js: 2.1.1
 - Third-party libraries (e.g., Angular, React, etc.): ReactJS 17.0.39

**Comment by pehamraza** [comment]
Having same issue on client browsers with twilio.js: 2.1.1 chrome on windows 10

**Comment by charliesantos** [comment]
As you mentioned, this is hard to reproduce. We haven't been able to see this in our test environment. Once you're able to reproduce, can you please provide debug logs?

**Comment by charliesantos** [comment]
Hey all, are you still seeing this issue?

**Comment by wjlroe** [comment]
We haven't seen this specific error since the latest twilio-voice JS SDK

**Comment by charliesantos** [comment]
Thanks @wjlroe . I'll close this now. Please feel free to follow up if you start seeing this issue again.

**Comment by brightsider** [comment]
I have this issue. Sentry caught it.
<img width="917" alt="image" src="https://github.com/twilio/twilio-voice.js/assets/4996231/4dde2804-9742-4757-9892-93c39909049e">

**Comment by charliesantos** [comment]
@brightsider thanks for the report. Do you have logs and repro steps?

**Comment by brightsider** [comment]
@charliesantos yes, I've full twilio logs
I can extend this batch if you needed
[logs-insights-results.csv](https://github.com/twilio/twilio-voice.js/files/14409549/logs-insights-results.csv)
